name: 'Sexual & Spiritual Violence Survivors Healing and Accountability Resource Exchange'
favicon: null
layout_spectrum: 0.4102029404602945
typography_spectrum: 0.9716619316022843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9473730160389096
  lightness: 0.39234195090830326
  saturation: 0.042378866113722324
  rhythmicContrast: 0.10498639405705035
purpose: []
