name: SSSHARE
favicon: null
layout_spectrum: 0.40634
typography_spectrum: 0.63575
title: 'SSSHARE: Sexual & Spiritual Violence Survivors Healing and Accountability Resource Exchange'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#989793'
    - '#8547aa'
    - '#37d8cc'
    - '#005e4f'
    - '#0d9b8c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
