typography_spectrum: 0.317720050457865
color:
  brandColors:
    - '#989793'
    - '#8547aa'
    - '#37d8cc'
    - '#005e4f'
    - '#0d9b8c'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8808772237971425
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jennifer A. Yoder
  email: jyoder@intoaccount.org
  url: 'http://www.intoaccount.org'
name: J. Yoder Consulting
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Violence Prevention
    id: 80feeb14-da03-4e84-b3c0-4b20ef3b13bd
    type: content
  - name: Communications
    id: 0b79ae2c-89b0-4235-946e-19d863ffc7be
    type: content
favicon: null
title: Jennifer A. Yoder
description: Data-Driven Consulting for Non-Profits and Businesses
purpose: []
