typography_spectrum: 0.61838
color:
  brandColors:
    - '#989793'
    - '#8547aa'
    - '#37d8cc'
    - '#005e4f'
    - '#0d9b8c'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.67699
analytics:
  google: null
  facebook: null
  twitter: null
name: Yoder Consulting
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Jennifer A. Yoder, Yoder Consulting'
purpose: []
