name: 'Sexual & Spiritual Violence Survivors Healing and Accountability Resource Exchange'
favicon: null
layout_spectrum: 0.40634
typography_spectrum: 0.63575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#989793'
    - '#8547aa'
    - '#37d8cc'
    - '#005e4f'
    - '#0d9b8c'
  brandStrength: 0.8125
  lightness: 0.39234195090830326
  saturation: 0.042378866113722324
  rhythmicContrast: 0.5
purpose: []
